DROP TABLE IF EXISTS owl;
DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS counters;

CREATE TABLE owl (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nom TEXT UNIQUE NOT NULL, 
    life INTEGER NOT NULL DEFAULT 10,
    mice INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE game (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    owl_id INTEGER NOT NULL,
    FOREIGN KEY (owl_id) REFERENCES owl (id)
);

CREATE TABLE counters (
    game_id INTEGER NOT NULL,
    day INTEGER NOT NULL DEFAULT 1,
    endOfDay BOOLEAN NOT NULL DEFAULT FALSE,
    mousePopulation INTEGER NOT NULL DEFAULT 4,
    FOREIGN KEY (game_id) REFERENCES game (id)
);