"""empty message

Revision ID: 5978cf7dcaeb
Revises: 
Create Date: 2020-01-03 19:23:16.596601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5978cf7dcaeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=True),
    sa.Column('life', sa.Integer(), nullable=True),
    sa.Column('mice', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owl_nom'), 'owl', ['nom'], unique=True)
    op.create_table('world',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owl_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('nightfall', sa.Boolean(), nullable=True),
    sa.Column('mouse_pop', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owl_id'], ['owl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world')
    op.drop_index(op.f('ix_owl_nom'), table_name='owl')
    op.drop_table('owl')
    # ### end Alembic commands ###
